create table if not exists users
(
    id       int primary key generated by default as identity,
    name     varchar(100) not null,
    email    varchar(50)  not null,
    password varchar(200) not null,
    role     varchar(50)  not null,
    status   varchar(50)  not null

);
create table if not exists request
(
    id             int primary key generated by default as identity,
    header         varchar(50)   not null,
    description    varchar(5000) not null,
    users_id       int           references users (id) on delete set null,
    status_request varchar(20)   not null,
    created_at     timestamp default now()
);
insert into users(name, password, email, role,status)
values (
           'admin','$2a$12$QyumFAO8XjRVPLoI0Z.piuoKbRH1f/7b37AcDgaXATuPKn2S5.zWe',
           'admin@admin','ADMIN','ACTIVE'
       );
insert into users(name, password, email, role,status)
values (
           'user','$2a$12$lJrrNI//hbFoTgvSe3rxn.zAO6.mPpjvg/VcYjKmeRyrfEMugZYd.',
           'user@mail.ru','USER','ACTIVE'
       );

insert into users(name, password, email, role,status)
values (
           'operator','$2a$12$FdHPv7XGPJWVG20Dziuun.kk4V9PT2b2MyA8mm3JHNvUgV/vj9.xy',
           'operator@mail.ru','OPERATOR','ACTIVE'
       );