create table if not exists users
(
    id       int primary key generated by default as identity,
    name     varchar(100) not null,
    email    varchar(50)  not null,
    password varchar(200) not null,
    role     varchar(50)  not null,
    status   varchar(50)  not null

);
create table if not exists request
(
    id             int primary key generated by default as identity,
    header         varchar(50)   not null,
    description    varchar(5000) not null,
    users_id       int           references users (id) on delete set null,
    status_request varchar(20)   not null,
    created_at     timestamp default now()
);
insert into users(name, password, email, role, status)
values ('admin', '$2a$12$/FMm4cg8zJ2220MT3gW99u..xMVnV5b5Uk0WGcu4Tw5QV6xJDUyTW',
        'a@', 'ADMIN', 'ACTIVE');
insert into users(name, password, email, role, status)
values ('user', '$2a$12$/FMm4cg8zJ2220MT3gW99u..xMVnV5b5Uk0WGcu4Tw5QV6xJDUyTW',
        'u@u', 'USER', 'ACTIVE');

insert into users(name, password, email, role, status)
values ('operator', '$2a$12$/FMm4cg8zJ2220MT3gW99u..xMVnV5b5Uk0WGcu4Tw5QV6xJDUyTW',
        'o@o', 'OPERATOR', 'ACTIVE');

