CREATE TABLE users
(
    id       int primary key generated by default as identity,
    name     varchar(100) not null,
    email    varchar(50)  not null,
    password varchar(200) not null,
    role     varchar(50)  not null,
    status   varchar(50)  not null
);

