CREATE TABLE request
(
    id             int primary key generated by default as identity,
    header         varchar(50)   not null,
    description    varchar(5000) not null,
    users_id       int           references users (id) on delete set null,
    status_request varchar(20)   not null,
    created_at     timestamp default now()
);